services:
  api:
    image: atendai/evolution-audio-converter:latest
    restart: unless-stopped
    ports:
      - 4040
    networks:
      - dokploy-network
    environment:
      - PORT=4040
      - API_KEY=${API_KEY}
    expose:
      - 4040


networks:
  dokploy-network:
    external: true
